### ISSUE TITLE
/user post route missing error msg for no email/pw

### ISSUE THREAD

**Issue by benjaminsinaiko** [donthedeveloper/site-builder#67]
When error handling was moved from route to model error messages weren't carried over.  

No email: 'You must provide an email address.'
No password: 'You must provide a password.'

**Comment by donthedeveloper** [comment]
@benjaminsinaiko is this fixed? Can we drag this to "Done"?

**Comment by benjaminsinaiko** [comment]
Yes, was added to another issue.
